#!/usr/bin/env python3
"""Emit data/complaints/headache/rules.yaml with verbatim NICE text."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _nice import quote, y  # noqa: E402

CG150 = "https://www.nice.org.uk/guidance/cg150"
NG12 = "https://www.nice.org.uk/guidance/ng12"
NG240 = "https://www.nice.org.uk/guidance/ng240"
LIC = "https://www.nice.org.uk/reusing-our-content/nice-uk-open-content-licence"

Q = {
    "cns_cancer": quote("ng12-lung", "1.9.1", "[2015]"),
    "headache_evaluate": quote("cg150", "1.1.1", "[2012]"),
    "meningitis_red_flag": quote("ng240", "1.1.4"),
    "meningococcal_red_flag": quote("ng240", "1.1.9"),
}
for k, v in Q.items():
    print(f"  {k:22s} {len(v):>4} chars  {v[:60]}...")

out = f"""# Headache -- NICE rules.
#
# GENERATED by scripts/build_rules_headache.py. Do not hand-edit text_verbatim.
#
# GAP, narrowed but not closed:
#  CG150 1.1.1 is the only NICE recommendation that names sudden-onset headache
#  and giant cell arteritis, so it is what the SAH and GCA paths now fire on.
#  Its verb is "evaluate ... and consider the need for further investigations
#  and/or referral" -- urgent, not emergency. The immediate-admission convention
#  for thunderclap headache and the same-day-referral convention for GCA are
#  clinical practice, not NICE, and are still unencoded. A clinician review pass
#  has to decide whether the tool may assert an urgency NICE does not state.

sources:
  cg150:
    type: guideline
    title: "Headaches in over 12s: diagnosis and management"
    url: {CG150}
    licence: {LIC}
    attribution: "(c) NICE 2021 Headaches in over 12s: diagnosis and management. Available from {CG150} All rights reserved. Subject to Notice of rights."
  ng12_hd:
    type: guideline
    title: "Suspected cancer: recognition and referral"
    url: {NG12}
    licence: {LIC}
    attribution: "(c) NICE 2015 Suspected cancer: recognition and referral. Available from {NG12} All rights reserved. Subject to Notice of rights."
  ng240:
    type: guideline
    title: "Meningitis (bacterial) and meningococcal disease: recognition, diagnosis and management"
    url: {NG240}
    licence: {LIC}
    attribution: "(c) NICE 2024 Meningitis (bacterial) and meningococcal disease: recognition, diagnosis and management. Available from {NG240} All rights reserved. Subject to Notice of rights."

rules:
  # CG150 1.1.1 is a long any-of list. Only the features the KB already has a
  # variable for are encoded; the rest of the list stays in the quoted text.
  cg150-headache-evaluate-1.1.1:
    complaints: [headache]
    min_matches: 1
    any_of:
      - {{var: headache_onset, op: in, value: [instant_maximal, minutes]}}
      - {{var: focal_neurology, op: "==", value: present}}
      - {{var: confusion_new, op: "==", value: present}}
      - {{var: scalp_tenderness, op: "==", value: present}}
      - {{var: jaw_claudication, op: "==", value: present}}
      - {{var: eye_pain_red_eye, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["headache_evaluate"])}
      source: cg150

  # NG240 1.1.4 is an all-of: the red flag combination requires every symptom.
  ng240-meningitis-red-flag-1.1.4:
    complaints: [headache]
    all_of:
      - {{var: fever_history, op: "==", value: present}}
      - {{var: neck_stiffness, op: "==", value: present}}
      - {{var: confusion_new, op: "==", value: present}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["meningitis_red_flag"])}
      source: ng240

  ng240-meningococcal-red-flag-1.1.9:
    complaints: [headache]
    min_matches: 1
    any_of:
      - {{var: non_blanching_rash, op: "==", value: present}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["meningococcal_red_flag"])}
      source: ng240

  ng12-cns-cancer-1.9.1:
    complaints: [headache]
    min_matches: 1
    any_of:
      - {{var: focal_neurology, op: "==", value: present}}
      - {{var: worse_on_waking, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["cns_cancer"])}
      source: ng12_hd
"""
Path("data/complaints/headache/rules.yaml").write_text(out)
print("\nwrote data/complaints/headache/rules.yaml")
