#!/usr/bin/env python3
"""Emit data/complaints/chest-pain/rules.yaml with verbatim NICE text."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _nice import quote, y  # noqa: E402

CG95 = "https://www.nice.org.uk/guidance/cg95"
NG158 = "https://www.nice.org.uk/guidance/ng158"
LIC = "https://www.nice.org.uk/reusing-our-content/nice-uk-open-content-licence"

Q = {
    "acs_symptoms": quote("cg95", "1.2.1.3", "[2010]"),
    "emergency": quote("cg95", "1.2.1.7", "[2010]"),
    "same_day": quote("cg95", "1.2.1.8", "[2010]"),
    "typicality": quote("cg95", "1.3.3.1", "[2010,"),
    "pe_cxr": quote("ng158", "1.1.15", "Pulmonary embolism rule-out"),
}
for k, v in Q.items():
    print(f"  {k:14s} {len(v):>4} chars  {v[:66]}...")

out = f"""# Chest pain -- NICE rules.
#
# GENERATED by scripts/build_rules_chest_pain.py. Do not hand-edit
# text_verbatim; re-run the builder.
#
# GAP: no NICE guideline covers aortic dissection recognition in primary care.
# The condition is in the pool and carries red-flag features, but no rule fires
# for it. Recorded rather than papered over.

sources:
  cg95:
    type: guideline
    title: "Recent-onset chest pain of suspected cardiac origin: assessment and diagnosis"
    url: {CG95}
    licence: {LIC}
    attribution: "(c) NICE 2016 Recent-onset chest pain of suspected cardiac origin: assessment and diagnosis. Available from {CG95} All rights reserved. Subject to Notice of rights."

rules:
  cg95-acs-symptoms-1.2.1.3:
    complaints: [chest-pain]
    min_matches: 1
    any_of:
      - {{var: chest_pain_duration, op: in, value: [over_15_minutes, constant]}}
      - {{var: autonomic_symptoms, op: "==", value: present}}
      - {{var: chest_pain_radiation, op: "==", value: arm_jaw_or_neck}}
    emit:
      kind: must_ask
      urgency: same_day
      text_verbatim: {y(Q["acs_symptoms"])}
      source: cg95

  cg95-emergency-referral-1.2.1.7:
    complaints: [chest-pain]
    all_of:
      - {{var: chest_pain_duration, op: in, value: [over_15_minutes, constant]}}
    min_matches: 1
    any_of:
      - {{var: autonomic_symptoms, op: "==", value: present}}
      - {{var: chest_pain_radiation, op: "==", value: arm_jaw_or_neck}}
      - {{var: chest_pain_character, op: "==", value: constricting}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["emergency"])}
      source: cg95

  cg95-same-day-1.2.1.8:
    complaints: [chest-pain]
    all_of:
      - {{var: chest_pain_character, op: "==", value: constricting}}
      - {{var: chest_pain_duration, op: "==", value: under_15_minutes}}
    emit:
      kind: referral
      urgency: same_day
      text_verbatim: {y(Q["same_day"])}
      source: cg95

  cg95-angina-typicality-1.3.3.1:
    complaints: [chest-pain]
    min_matches: 2
    any_of:
      - {{var: chest_pain_character, op: "==", value: constricting}}
      - {{var: chest_pain_trigger, op: "==", value: exertion}}
      - {{var: chest_pain_relief, op: "==", value: rest_or_gtn}}
    emit:
      kind: must_ask
      urgency: urgent
      text_verbatim: {y(Q["typicality"])}
      source: cg95

  ng158-pe-chest-pain-1.1.15:
    complaints: [chest-pain]
    min_matches: 1
    any_of:
      - {{var: pleuritic_pain, op: "==", value: present}}
      - {{var: clinical_dvt_signs, op: "==", value: present}}
      - {{var: recent_immobility, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: same_day
      text_verbatim: {y(Q["pe_cxr"])}
      source: ng158
"""
Path("data/complaints/chest-pain/rules.yaml").write_text(out)
print("\nwrote data/complaints/chest-pain/rules.yaml")
