#!/usr/bin/env python3
"""Emit data/complaints/acute-cough/rules.yaml with verbatim NICE text.

Quotes are sliced out of the files fetched by fetch_nice.py and asserted to be
present, so verbatim fidelity holds by construction rather than by transcription.
The NICE UK Open Content Licence forbids amending the wording of a published
recommendation; whitespace collapsing is the only permitted change.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _nice import quote, y  # noqa: E402


NG12 = "https://www.nice.org.uk/guidance/ng12"
NG158 = "https://www.nice.org.uk/guidance/ng158"
NG250 = "https://www.nice.org.uk/guidance/ng250"
NG253 = "https://www.nice.org.uk/guidance/ng253"
LIC = "https://www.nice.org.uk/reusing-our-content/nice-uk-open-content-licence"

Q = {
    "ng12_1_1_1": quote("ng12-lung", "1.1.1", "[2015]"),
    "ng12_1_1_2": quote("ng12-lung", "1.1.2", "[2015]"),
    "ng12_1_1_3": quote("ng12-lung", "1.1.3", "[2015]"),
    "ng158_1_1_15": quote("ng158", "1.1.15", "Pulmonary embolism rule-out"),
    "ng158_1_1_17": quote("ng158", "1.1.17", "Table 2"),
    "ng250_1_2_3": quote("ng250", "1.2.3", "[2025]"),
    "ng158_wells": (
        "Table 2 Two-level PE Wells score Clinical feature Points Clinical signs "
        "and symptoms of DVT (minimum of leg swelling and pain with palpation of "
        "the deep veins) 3 An alternative diagnosis is less likely than PE 3 Heart "
        "rate more than 100 beats per minute 1.5 Immobilisation for more than 3 "
        "days or surgery in the previous 4 weeks 1.5 Previous DVT/PE 1.5 "
        "Haemoptysis 1 Malignancy (on treatment, treated in the last 6 months, or "
        "palliative) 1 Clinical probability simplified score Points PE likely More "
        "than 4 points PE unlikely 4 points or less"),
    "ng253_1_5_2": quote("ng253-risk", "1.5.2", "[2016"),
}
for k, v in Q.items():
    print(f"  {k:14s} {len(v):>4} chars  {v[:70]}...")



out = f"""# Acute cough / breathlessness -- NICE rules.
#
# GENERATED by scripts/build_rules_acute_cough.py from .workbench/nice/.
# text_verbatim is sliced directly out of the fetched guideline text; do not
# hand-edit it. Re-run the builder instead.
#
# Rules are single-shot predicates over the answer set. They never chain and
# never write to the ranking -- they emit actions only.

sources:
  ng12:
    type: guideline
    title: "Suspected cancer: recognition and referral"
    url: {NG12}
    licence: {LIC}
    attribution: "(c) NICE 2015 Suspected cancer: recognition and referral. Available from {NG12} All rights reserved. Subject to Notice of rights."
  ng158:
    type: guideline
    title: "Venous thromboembolic diseases: diagnosis, management and thrombophilia testing"
    url: {NG158}
    licence: {LIC}
    attribution: "(c) NICE 2020 Venous thromboembolic diseases: diagnosis, management and thrombophilia testing. Available from {NG158} All rights reserved. Subject to Notice of rights."
  ng250:
    type: guideline
    title: "Pneumonia: diagnosis and management"
    url: {NG250}
    licence: {LIC}
    attribution: "(c) NICE 2025 Pneumonia: diagnosis and management. Available from {NG250} All rights reserved. Subject to Notice of rights."
    note: "Replaced CG191, which NICE withdrew on 31 October 2023."
  ng253:
    type: guideline
    title: "Suspected sepsis in people aged 16 or over"
    url: {NG253}
    licence: {LIC}
    attribution: "(c) NICE 2024 Suspected sepsis in people aged 16 or over. Available from {NG253} All rights reserved. Subject to Notice of rights."
    note: "Replaced NG51, which NICE split into NG253/NG254/NG255 on 19 March 2024."

variables:
  finger_clubbing:
    prompt: "Is there finger clubbing?"
    modality: examination
    cost: 1
    values: [present, absent, unknown]

rules:
  ng12-lung-1.1.1:
    complaints: [acute-cough]
    all_of:
      - {{var: age_years, op: in, value: [forty_to_64, sixty_five_or_over]}}
      - {{var: cough_character, op: "==", value: blood_stained}}
    emit:
      kind: referral
      urgency: urgent
      text_verbatim: {y(Q["ng12_1_1_1"])}
      source: ng12

  # NG12 1.1.2 has two limbs. Split so each is faithful: two-or-more symptoms
  # regardless of smoking, or ever-smoked plus one. Same verbatim text on both.
  ng12-lung-1.1.2-two-symptoms:
    complaints: [acute-cough]
    all_of:
      - {{var: age_years, op: in, value: [forty_to_64, sixty_five_or_over]}}
    min_matches: 2
    any_of:
      - {{var: cough_duration, op: in, value: [three_to_8_weeks, over_8_weeks]}}
      - {{var: fatigue, op: "==", value: present}}
      - {{var: breathlessness, op: in, value: [on_exertion, at_rest]}}
      - {{var: chest_pain_present, op: "==", value: present}}
      - {{var: weight_loss, op: "==", value: present}}
      - {{var: appetite_loss, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["ng12_1_1_2"])}
      source: ng12

  ng12-lung-1.1.2-smoker-one-symptom:
    complaints: [acute-cough]
    all_of:
      - {{var: age_years, op: in, value: [forty_to_64, sixty_five_or_over]}}
      - {{var: ever_smoked, op: in, value: [former, current]}}
    min_matches: 1
    any_of:
      - {{var: cough_duration, op: in, value: [three_to_8_weeks, over_8_weeks]}}
      - {{var: fatigue, op: "==", value: present}}
      - {{var: breathlessness, op: in, value: [on_exertion, at_rest]}}
      - {{var: chest_pain_present, op: "==", value: present}}
      - {{var: weight_loss, op: "==", value: present}}
      - {{var: appetite_loss, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["ng12_1_1_2"])}
      source: ng12

  ng12-lung-1.1.3:
    complaints: [acute-cough]
    all_of:
      - {{var: age_years, op: in, value: [forty_to_64, sixty_five_or_over]}}
    any_of:
      - {{var: finger_clubbing, op: "==", value: present}}
      - {{var: cough_duration, op: "==", value: over_8_weeks}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["ng12_1_1_3"])}
      source: ng12

  ng158-pe-1.1.15:
    complaints: [acute-cough]
    any_of:
      - {{var: cough_character, op: "==", value: blood_stained}}
      - {{var: pleuritic_pain, op: "==", value: present}}
      - {{var: breathlessness, op: "==", value: at_rest}}
    emit:
      kind: investigation
      urgency: same_day
      text_verbatim: {y(Q["ng158_1_1_15"])}
      source: ng158

  ng158-pe-1.1.17:
    complaints: [acute-cough]
    any_of:
      - {{var: clinical_dvt_signs, op: "==", value: present}}
      - {{var: pe_alternative_less_likely, op: "==", value: alternative_less_likely}}
      - {{var: heart_rate_over_100, op: "==", value: present}}
      - {{var: recent_immobility, op: "==", value: present}}
    emit:
      kind: must_ask
      urgency: same_day
      text_verbatim: {y(Q["ng158_1_1_17"])}
      source: ng158

  # CRB65 is a count, so min_matches expresses it exactly. Two or more is the
  # threshold NICE gives for referral; on one point the recommendation is
  # primary care with safety netting, which is not what this text says.
  ng250-cap-1.2.3:
    complaints: [acute-cough]
    min_matches: 2
    any_of:
      - {{var: confusion_new, op: "==", value: present}}
      - {{var: respiratory_rate, op: "==", value: thirty_or_over}}
      - {{var: low_blood_pressure, op: "==", value: present}}
      - {{var: age_years, op: "==", value: sixty_five_or_over}}
    emit:
      kind: referral
      urgency: same_day
      text_verbatim: {y(Q["ng250_1_2_3"])}
      source: ng250

  # The two-level PE Wells score, weighted rather than counted: two 1.5-point
  # items are not one 3-point item, and the threshold is more than 4.
  #
  # All seven criteria, totalling 12 points. Haemoptysis is read off
  # cough_character rather than a variable of its own.
  ng158-pe-wells-table-2:
    complaints: [acute-cough, chest-pain]
    min_score: 4.5
    any_of:
      - {{var: clinical_dvt_signs, op: "==", value: present, points: 3}}
      - {{var: pe_alternative_less_likely, op: "==", value: alternative_less_likely, points: 3}}
      - {{var: heart_rate_over_100, op: "==", value: present, points: 1.5}}
      - {{var: recent_immobility, op: "==", value: present, points: 1.5}}
      - {{var: previous_dvt_pe, op: "==", value: present, points: 1.5}}
      - {{var: cough_character, op: "==", value: blood_stained, points: 1}}
      - {{var: active_malignancy, op: "==", value: present, points: 1}}
    emit:
      kind: investigation
      urgency: same_day
      text_verbatim: {y(Q["ng158_wells"])}
      source: ng158

  ng253-sepsis-1.5.2:
    complaints: [acute-cough]
    any_of:
      - {{var: confusion_new, op: "==", value: present}}
      - {{var: respiratory_rate, op: "==", value: thirty_or_over}}
      - {{var: low_blood_pressure, op: "==", value: present}}
      - {{var: oxygen_saturation, op: "==", value: under_92}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["ng253_1_5_2"])}
      source: ng253
"""
Path("data/complaints/acute-cough/rules.yaml").write_text(out)
print("\nwrote data/complaints/acute-cough/rules.yaml")
