#!/usr/bin/env python3
"""Emit data/complaints/headache/rules.yaml with verbatim NICE text."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _nice import quote, y  # noqa: E402

NG12 = "https://www.nice.org.uk/guidance/ng12"
NG240 = "https://www.nice.org.uk/guidance/ng240"
LIC = "https://www.nice.org.uk/reusing-our-content/nice-uk-open-content-licence"

Q = {
    "cns_cancer": quote("ng12-lung", "1.9.1", "[2015]"),
    "meningitis_red_flag": quote("ng240", "1.1.4"),
    "meningococcal_red_flag": quote("ng240", "1.1.9"),
}
for k, v in Q.items():
    print(f"  {k:22s} {len(v):>4} chars  {v[:60]}...")

out = f"""# Headache -- NICE rules.
#
# GENERATED by scripts/build_rules_headache.py. Do not hand-edit text_verbatim.
#
# GAPS, recorded rather than papered over:
#  - No current NICE guideline covers subarachnoid haemorrhage recognition in
#    primary care. The condition is pooled with red-flag features but no rule
#    fires for it.
#  - Giant cell arteritis likewise has no NICE recognition guideline; the
#    same-day-referral convention is clinical practice, not NICE, so it is not
#    encoded as a rule here.
# Both are the strongest argument in the KB for a clinician review pass.

sources:
  ng12_hd:
    type: guideline
    title: "Suspected cancer: recognition and referral"
    url: {NG12}
    licence: {LIC}
    attribution: "(c) NICE 2015 Suspected cancer: recognition and referral. Available from {NG12} All rights reserved. Subject to Notice of rights."
  ng240:
    type: guideline
    title: "Meningitis (bacterial) and meningococcal disease: recognition, diagnosis and management"
    url: {NG240}
    licence: {LIC}
    attribution: "(c) NICE 2024 Meningitis (bacterial) and meningococcal disease: recognition, diagnosis and management. Available from {NG240} All rights reserved. Subject to Notice of rights."

rules:
  # NG240 1.1.4 is an all-of: the red flag combination requires every symptom.
  ng240-meningitis-red-flag-1.1.4:
    complaints: [headache]
    all_of:
      - {{var: fever_history, op: "==", value: present}}
      - {{var: neck_stiffness, op: "==", value: present}}
      - {{var: confusion_new, op: "==", value: present}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["meningitis_red_flag"])}
      source: ng240

  ng240-meningococcal-red-flag-1.1.9:
    complaints: [headache]
    min_matches: 1
    any_of:
      - {{var: non_blanching_rash, op: "==", value: present}}
    emit:
      kind: escalation
      urgency: emergency
      text_verbatim: {y(Q["meningococcal_red_flag"])}
      source: ng240

  ng12-cns-cancer-1.9.1:
    complaints: [headache]
    min_matches: 1
    any_of:
      - {{var: focal_neurology, op: "==", value: present}}
      - {{var: worse_on_waking, op: "==", value: present}}
    emit:
      kind: investigation
      urgency: urgent
      text_verbatim: {y(Q["cns_cancer"])}
      source: ng12_hd
"""
Path("data/complaints/headache/rules.yaml").write_text(out)
print("\nwrote data/complaints/headache/rules.yaml")
